# Generated by Django 3.0.8 on 2020-07-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userimage',
            field=models.ImageField(null=True, upload_to='user_img/profile/'),
        ),
    ]
